# Generated by Django 4.0.4 on 2022-07-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '8. Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '9. Order Items'},
        ),
    ]
